api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

# Views
from api.views import *

urlpatterns = [
    path('login/<slug:imei>/', Login.as_view()),
    path('sincronizacion/<int:ruta>/', Sincronizacion.as_view()),
    path('cierre/caja/<int:caja>/', CierreCaja.as_view()),
    path('transacciones/<slug:imei>/', Transacciones.as_view()),
    path('inversiones/<slug:imei>/', Inversiones.as_view()),
    path('rutas/', Rutas.as_view()),

    path('sincronizacion/movimientos/', SincronizacionMovimientos.as_view()),
    path('sincronizacion/clientes/editados/', SincronizacionClientesEditados.as_view()),
    path('sincronizacion/pagos/', SincronizacionPagos.as_view()),
    path('sincronizacion/clientes/', SincronizacionClientes.as_view()),
    path('sincronizacion/ventas/', SincronizacionVentas.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import Login, logout, PolitivasPrivacidad

from rest_framework.documentation import include_docs_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('',Login.as_view(), name="login" ),
    path('logout/', logout, name="logout"),
    path('rutas/', include('rutas.urls')),
    path('clientes/',include('clientes.urls')),
    path('ventas/',include('ventas.urls')),
    path('pagos/',include('pagos.urls')),
    path('caja/', include('caja.urls')),
    path('movimientos/', include('movimientos.urls')),
    path('retiros/', include('retiros.urls')),
    path('politicas_de_privacidad/',PolitivasPrivacidad.as_view() ,name="politivas_de_privacidad"),

    #URLS API
    path('docs/', include_docs_urls(title='Django API')),
    path('api/', include('api.urls')),


]

retiros/urls.py
from django.urls import path
from retiros.views import TransaccionCrear, TransaccionListar, TransaccionEditar, TransaccionEliminar, \
							InversionListar, InversionCrear, InversionEditar, Buscar

app_name = "retiros"

urlpatterns = [
	path('listar/', TransaccionListar.as_view(), name = "listar_retiros"),
	path('crear/', TransaccionCrear.as_view(), name = "crear_retiro"),
	path('editar/<int:pk>/', TransaccionEditar.as_view(), name = "editar_retiro"),
	path('eliminar/<int:pk>', TransaccionEliminar.as_view(), name = "eliminar_retiro"),

	path('inversiones/listar', InversionListar.as_view(), name = "listar_inversiones"),
	path('inversiones/crear/', InversionCrear.as_view(), name = "crear_inversion"),
	path('inversiones/editar/<int:pk>/', InversionEditar.as_view(), name = "editar_inversion"),

	path('busqueda/<slug:busqueda>/', Buscar.as_view(), name="busqueda"),
]

rutas/urls.py
from rutas.views import Base, RutaListar, RutaCrear, RutaEditar, ImeiListar, ImeiCrear, ImeiEditar, RutaEliminar, ImeiEliminar
from django.urls import path
from rutas.ajax import cambiar_estado, cierre_ruta

app_name = "rutas"

urlpatterns = [
    path('base/', Base.as_view(), name="base"),
    path('listar/', RutaListar.as_view(), name = "listar_rutas"),
    path('crear/', RutaCrear.as_view(), name = "crear_ruta"),
    path('editar/<int:pk>/', RutaEditar.as_view(), name = "editar_ruta"),
    path('listar/imei/', ImeiListar.as_view(), name = "listar_imei"),
    path('crear/imei/', ImeiCrear.as_view(), name = "crear_imei"),
    path('editar/imei/<int:pk>/', ImeiEditar.as_view(), name = "editar_imei"),
    path('eliminar/<int:pk>/',RutaEliminar.as_view(), name='eliminar'),
    path('imei/eliminar/<int:pk>/',ImeiEliminar.as_view(), name='eliminar_imei'),

    #AJAX
    path('estado/', cambiar_estado, name = "cambiar_estado_ruta"),
    path('cierre/ruta/', cierre_ruta, name = "pagos_cierre_ruta"),

]

usuarios/urls.py
from usuarios.views import *
from django.urls import path
from usuarios.views import ComuinidadCrear, ComuinidadListar, UsuariosListar, \
								UsuarioCrear, UsuarioCrearAdmin, PermisosUsuario, UsuarioRutaActualizar
from usuarios.ajax import cambiar_estado_comunidad, cambiar_estado_usuario, \
							cambiar_permisos_secretaria
app_name = "usuarios"

urlpatterns = [
	#URLS de app Usuarios
	path('crear-comunidad/',ComuinidadCrear.as_view(), name="crear_comunidad"),
	path('listar-comunidad/',ComuinidadListar.as_view(), name="listar_comunidad"),
	path('listar-usuarios/',UsuariosListar.as_view(), name = "listar_usuarios" ),
	path('crear-usuarios/', UsuarioCrear.as_view(), name = "crear_usuarios"),
	path('crear-usuarios/admin', UsuarioCrearAdmin.as_view(), name = "crear_usuarios_admin"),
	path('editar-usuarios/<int:pk>/', UsuarioEditar.as_view(), name = "editar_usuario"),
	path('gestionar/<int:user>/', PermisosUsuario.as_view(), name="gestionar_usuario" ),
	path('agregar/rutas/secretaria/<int:pk>', UsuarioRutaActualizar.as_view(), name="rutas_secretaria"),

	#URLS de ajax Usuarios cambiar_estado_usuario UsuarioEditar
	path('estado/comunidad/',cambiar_estado_comunidad, name="cambiar_estado_comunidad" ),
	path('estado/usuario/',cambiar_estado_usuario, name="cambiar_estado_usuario" ),
	path('permisos/usuario/', cambiar_permisos_secretaria, name="cambiar_permisos_secretaria")
]

pagos/models.py
from django.db import models
from ventas.models import Venta
from caja.models import Caja
from django.urls import reverse
from django.db.models import Sum, Count
from django_extensions.db.models import TimeStampedModel

#Modelo Motivo del no pago
class Motivo(models.Model):
	descripcion = models.CharField(max_length=50)
	def __str__(self):
		return self.descripcion

#Modelo de Tipo Pago
class TipoPago(models.Model):
	descripcion = models.CharField(max_length=20)
	motivo = models.BooleanField(default=False)
	def __str__(self):
		return self.descripcion

#Modelo Pago
class Pago(TimeStampedModel):
	valor = models.FloatField(default=0)
	tipo_pago = models.ForeignKey(TipoPago, on_delete = models.CASCADE)
	motivo = models.ForeignKey(Motivo, on_delete = models.CASCADE, null=True, blank=True)
	venta = models.ForeignKey(Venta, on_delete = models.CASCADE)
	caja = models.ForeignKey(Caja, on_delete = models.CASCADE)

	def url_absoluta(self):
		return reverse("pagos:listar_pagos", kwargs={'id_venta':self.venta.pk})

	def saldo(self):
		data = Pago.objects.filter(venta=self.venta, pk__lte=self.pk).aggregate(Sum('valor'))
		if data['valor__sum']:
			return self.venta.valor_venta_interes()-data['valor__sum']
		else:
			return self.venta.valor_venta_interes()

	def delete(self, *args, **kwargs):
		no_sincro = self.caja.ventanocobrado_set.all().order_by("-pk").first()
		if no_sincro:
			no_sincro.venta.add(self.venta)
			suma_pagos = self.venta.suma_pagos().aggregate(Sum('valor'))
			if (self.venta.saldo()  + self.valor > 0):
				self.venta.no_cobrado = True
				self.venta.save()
		super().delete(*args, **kwargs)  # Call the "real" delete() method.

	def save(self, *args, **kwargs):
		ventas = self.caja.ventanocobrado_set.all().order_by("-pk").first()
		if ventas:
			ventas.venta.remove(self.venta)
			validardor = ventas.venta.all()
		pagos = Pago.objects.filter(caja=self.caja, venta=self.venta).count()
		if pagos == 0:
			super().save(*args, **kwargs)  # Call the "real" save() method.
		try:
			if (self.venta.saldo() <= 0):
				self.venta.no_cobrado = False
				self.venta.save()
		except TypeError:
			pass

	def duplicada(self):
		pagos = Pago.objects.filter(caja=self.caja, venta=self.venta).count()
		if pagos > 1 :
			return True
		else:
			return False

# Create your models here.

templates/base/base.html
<!--Base de Busat-->
{%load static%}
<!DOCTYPE html>
<html>
<head>
	{%block title%}Sistema de Informacion{%endblock%}
	{%include "base/header.html"%}
</head>
<body>
	{%include "base/navbar.html"%}
	<div class="wrapper b-wrapper bs-bg-grey-dark">
        <div class="container-fluid">
			{%block content%}
			
			{%endblock%}
		</div>
	</div>
</body>
</html>
<!--Base de Busat-->

templates/base/crear.html
{%extends 'base/base.html'%}
{%block content%}
<div class="row">   
    <div class="col-5 mx-auto">
        <div class="card-box">
            <div class="title text-center pt-3">
                <h3 class="m-t-0 header-title">Crear Ruta</h3>
            </div>
            <hr class="col-4 mx-auto">
            <!--Card content-->
            <div class="row">
                <div class="col-12 mx-auto">
                    <div class="card-body pt-0">
                        <!-- Form -->
                        <form class="b-form" class="text-center" style="color: #757575;">
                            <div class="row b-content-form">
                                <!-- Nombre -->
                                <div class="md-form col-12">
                                    <input type="text" id="materialLoginFormEmail" class="form-control pb-1 text-uppercase">
                                    <label class="pl-2" for="materialLoginFormEmail">Nombre</label>
                                </div>

                                <!-- Imei -->
                                <div class="md-form col-6">
                                    <input type="text" id="materialLoginFormPassword" class="form-control pb-1">
                                    <label class="pl-2" for="materialLoginFormPassword">Imei</label>
                                </div>

                                <!-- Clave -->
                                <div class="md-form col-6">
                                    <input type="text" id="materialLoginFormPassword" class="form-control pb-1">
                                    <label class="pl-2" for="materialLoginFormPassword">Clave</label>
                                </div>

                                <div class="col-12 text-center px-0">
                                    <a class="btn btn-outline-danger waves-effect btn-rounded px-5" href="">Cancelar</a>
                                    <button class="btn btn-outline-info waves-effect btn-rounded px-5" type="submit">Sign in</button>
                                </div>
                            </div>

                        </form>
                        <!-- Form -->
                     </div>
                </div>
            </div>
        </div>    

        

    </div>
</div>
{% endblock %}

templates/base/footer.html
{%load static%}
<!-- Footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                2019 © BUSAT - All right reserved - Soluciones Inmediatas
                <a href="{%url 'politivas_de_privacidad' %}">Politicas de privacidad</a>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery  -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script><!-- Popper for Bootstrap --><!-- Tether for Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/waves.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<!-- Required datatable js -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Switchery -->
<script src="{% static 'plugins/switchery/switchery.min.js' %}"></script>

<!-- Modal-Effect -->
<script src="{% static 'plugins/custombox/dist/custombox.min.js' %}"></script>
<script src="{% static 'plugins/custombox/dist/legacy.min.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/jquery.core.js' %}"></script>
<script src="{% static 'js/jquery.app.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function() {

        // Default Datatable
        $('#datatable').DataTable();

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );

</script>
<script type="text/javascript">
    $(document).ready(function() {

        // Default Datatable
        $('#datatable').DataTable();

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );

</script>
<script type="text/javascript">
    function pk_modelo(caja, venta, pk, cuota){
        document.getElementById("cajita").value = caja;
        document.getElementById("id_venta").value = venta;
        $("#venta_info").html(`<ul>
                                    <li>Saldo: ${pk}</li>
                                    <li>cuota: ${cuota}</li>
                                </ul>`);
    }
</script>
<script type="text/javascript">
		
	$( ".motivo" ).change(function() {
		console.log($('#id_tipo_pago option:selected').text())
  		if ($('#id_tipo_pago option:selected').text() == 'DINERO'){
			$('#motivo_taps').attr('style','display:none');
            document.getElementById("id_valor").removeAttribute("readonly");
			$('#id_motivo').val() = "";
		}else{
			document.getElementById("motivo_taps").removeAttribute("style");
            $('#id_valor').attr('readonly','');
		}
	});
</script>
<script type="text/javascript">
    $(document).ready(function(){
    $('#motivo').attr('style','display:none');
})
</script>
<!-- End Footer -->

templates/base/header.html
<!--HEADER-->
{%load static%}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<link rel="shortcut icon" href="{%static 'images/favicon.ico' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link rel="shortcut icon" href="assets/images/favicon.ico">
        <!-- Modals UI -->
<link href="{%static 'plugins/custombox/dist/custombox.min.css' %}" rel="stylesheet">

<!-- Switchery -->
<link href="{%static 'plugins/switchery/switchery.min.css' %}" rel="stylesheet" />
<link href="{%static 'plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />

<!-- DataTables -->
<link href="{%static 'plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<!-- App css -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/icons.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/busat-style.css' %}" rel="stylesheet" type="text/css" />
<!-- Material Design Bootstrap 
  <link href="{% static 'css/mdb.css' %}" rel="stylesheet"> -->

<script src="{% static 'js/modernizr.min.js'%}"></script>
<!--HEADER-->

templates/base/javascripts.html
{%load static%}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script><!-- Popper for Bootstrap --><!-- Tether for Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/waves.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>

<script src="{% static 'plugins/switchery/switchery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/multiselect/js/jquery.multi-select.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/jquery-quicksearch/jquery.quicksearch.js' %}"></script>
<script src="{% static 'plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' %}" type="text/javascript"></script>
<script src="{% static 'plugins/bootstrap-inputmask/bootstrap-inputmask.min.js' %}" type="text/javascript"></script>

<!-- Required datatable js -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Modal-Effect -->
<script src="{% static 'plugins/custombox/dist/custombox.min.js' %}"></script>
<script src="{% static 'plugins/custombox/dist/legacy.min.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/jquery.core.js' %}"></script>
<script src="{% static 'js/jquery.app.js' %}"></script>

<!-- MDB core JavaScript 
<script type="text/javascript" src="{% static 'js/mdb.js' %}"></script> -->

<script type="text/javascript">
    $(document).ready(function() {

        // Default Datatable
        $('#datatable').DataTable();

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

<script>
	$(document).ready(function() {
 		$('.mdb-select').materialSelect();
	});
</script>
<script type="text/javascript">
    function pk_modelo(caja, venta){

        document.getElementById("id_caja").value = caja;
        document.getElementById("id_venta").value = venta;

    }
</script>
<script type="text/javascript">
	$( ".motivo_taps" ).change(function() {
		if ($('id_motivo').val() == 1){
			document.getElementById("motivo_tap").removeAttribute("style");
		}else{
			$('#motivo_tap').attr('style','display:none');
		}

	});
    function motivo_tab(){
        document.getElementById("motivo").removeAttribute("style");
    }
</script>
<script type="text/javascript">
    $(document).ready(function(){
    $('#motivo_tap').attr('style','display:none');
}
</script>

templates/base/listar.html
{%extends 'base/base.html'%}
{%block content%}
<div class="row">   
    <div class="col-12">
        <div class="card-box">
            <div class="title">
                <h4 class="m-t-0 header-title">Listado de Retiros</h4>
            </div>
            <hr class="">
            <div class="table-responsive">
                <table id="datatable" class="table table-bordered table-hover">
                    <thead>
                        <th>Fecha</th>
                        <th>Ruta</th>
                        <th>Valor</th>
                        <th>Depositado</th>
                        <th>User</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>01/02/2018</td>
                            <td>Andres Arari</td>
                            <td>5000</td>
                            <td>Gustavo itau</td>
                            <td>Diana</td>
                        </tr>
                        <tr>
                            <td>04/09/2018</td>
                            <td>Camilo Xinguara</td>
                            <td>10000</td>
                            <td>5000 Bey 5000 Rey</td>
                            <td>Lina</td>
                        </tr>
                        <tr>
                            <td>01/22/2019</td>
                            <td>Yesica Campo Maior</td>
                            <td>6000</td>
                            <td>Lina Brasil</td>
                            <td>Cindy</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base/login.html
<!--LOGIN.HTML-->
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<!--HEADER DE BASE-->
	{%include "base/header.html"%}
	<!--HEADER DE BASE-->
</head>
<body>
	<div class="wrapper-page">
		<div class="card">
			<div class="card-body">

		        <div class="text-center">
		            <a href="index.html" class="logo-lg"><i class="mdi mdi-radar"></i> <span>BUSAT</span> </a>
		        </div>
		        {%if form.errors.username%}
		        	{{form.errors.username}}
		        {%endif%}
		        {%if form.errors%}
		        	{{form.error_messages.invalid_login}}
		        {%endif%}
		        <form class="form-horizontal m-t-20" method="post" action="{%url 'login'%}">{%csrf_token%}

		            <div class="form-group row">
		                <div class="col-12">
		                    <div class="input-group">
		                        <div class="input-group-prepend">
		                            <span class="input-group-text"><i class="mdi mdi-account"></i></span>
		                        </div>
		                        <input placeholder="Usuario" class="form-control" type="text" name="username" autofocus="" maxlength="254" required="" id="id_username">
		                    </div>
		                </div>
		            </div>

		            <div class="form-group row">
		                <div class="col-12">
		                    <div class="input-group">
		                        <div class="input-group-prepend">
		                            <span class="input-group-text"><i class="mdi mdi-radar"></i></span>
		                        </div>
		                        <input class="form-control" type="password" name="password" required="" id="id_password" placeholder="Contraseña">
		                    </div>
		                </div>
		            </div>

		            <div class="form-group row">
		                <div class="col-12">
		                    <div class="checkbox checkbox-primary">
		                        <input id="checkbox-signup" type="checkbox">
		                        <label for="checkbox-signup">
		                            Recordar Contraseña
		                        </label>
		                    </div>

		                </div>
		            </div>

		            <div class="form-group text-center m-t-20">
		                <div class="col-xs-12">
		                    <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">Ingresar
		                    </button>
		                </div>
		            </div>
		        </form>
		    </div>
		</div>
	</div>
</body>
<!--Scripts de base-->
{%include "base/javascripts.html"%}
{%include "base/footer.html"%}
</html>
<!--LOGIN.HTML-->

templates/base/navbar.html
{%load static%}
<!-- Navigation Bar-->
<header id="topnav">
    <div class="topbar-main bs-bg-primary">
        <div class="container-fluid">

            <!-- Logo container-->
            <div class="logo">
                <!-- Text Logo -->
                <a href="{% url 'rutas:listar_rutas' %}" class="">
                    <span>
                        <img src="{% static 'images/bs-icon-logo.svg' %}" height="44" alt="">
                        <img src="{% static 'images/bs-typo-logo.svg' %}" height="30" alt="">
                    </span>
                </a>
                <!-- Image Logo -->
                <!--<a href="index.html" class="logo">-->
                    <!--<img src="assets/images/logo_dark.png" alt="" height="24" class="logo-lg">-->
                    <!--<img src="assets/images/logo_sm.png" alt="" height="24" class="logo-sm">-->
                <!--</a>-->

            </div>
            <!-- End Logo container-->


            <div class="menu-extras topbar-custom">

                <ul class="list-inline float-right mb-0">

                    <li class="menu-item list-inline-item">
                        <!-- Mobile menu toggle-->
                        <a class="navbar-toggle nav-link text-white">
                            <i class="ti-menu"></i>
                        </a>
                        <!-- End mobile menu toggle-->
                    </li>

                    <li class="list-inline-item dropdown notification-list">
                        <a class="nav-link dropdown-toggle waves-effect nav-user bs-bg-secondary" data-toggle="dropdown" href="#" role="button"
                           aria-haspopup="false" aria-expanded="false">
                            <i class=" mdi mdi-account bs-font-28 text-white"></i>
                            <!--<img src="" alt="user" class="rounded-circle">-->
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5 class="text-overflow"><small class="text-white">Welcome! {{user}}</small> </h5>
                            </div>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="mdi mdi-lock-open"></i> <span>Lock Screen</span>
                            </a>

                            <!-- item-->
                            <a href="{%url 'logout'%}" class="dropdown-item notify-item">
                                <i class="mdi mdi-logout"></i> <span>Logout</span>
                            </a>
                        </div>
                    </li>

                </ul>
            </div>
            <!-- end menu-extras -->

            <div class="clearfix"></div>

        </div> <!-- end container -->
    </div>
    <!-- end topbar-main -->
    <div class="navbar-custom bs-bg-secondary">
        <div class="container-fluid">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">

                    <!--<li class="has-submenu">
                        <a href="index.html"><i class="ti-home"></i>Inicio</a>
                    </li>-->
                    {%if perms.usuarios.is_superadmin%}
                        <li class="has-submenu">
                            <a href="{%url 'usuarios:listar_comunidad'%}"><i class="ti-settings"></i>Comunidades</a>
                        </li>
                        <li class="has-submenu">
                            <a href="{%url 'usuarios:listar_usuarios'%}"><i class="ti-user"></i>Usuarios</a>
                        </li>
                    {%endif%}
                    {%if not request.user.is_staff%}
                        <li class="nav-item dropdown class">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="ti-map-alt"></i>Rutas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% if not perms.usuarios.is_secretaria%}
                                    <a class="dropdown-item bs-text-primary" href="{%url 'rutas:listar_imei'%}">Listar Imei</a>
                                {% endif %}    
                                <div class="dropdown-divider"></div>
                                    <a class="dropdown-item bs-text-primary" href="{%url 'rutas:listar_rutas'%}">Listar Rutas</a>
                            </div>
                        </li> 
                        <li class="nav-item dropdown class">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="ti-credit-card"></i>Retiros
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item bs-text-primary" href="{%url 'retiros:listar_retiros'%}">Listar Retiros</a>  
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item bs-text-primary" href="{%url 'retiros:listar_inversiones'%}">Listar Inversiones</a>
                            </div>
                        </li> 
                        {% if perms.usuarios.is_admincomunidad %}
                            <li class="has-submenu">
                                <a href="{%url 'usuarios:listar_usuarios'%}"><i class="mdi mdi-account-multiple-outline text-white bs-font-24"></i>Usuarios</a>
                            </li>
                        {%endif%}
                    {%endif%}
                </ul>   

                <!-- End navigation menu -->
            </div> <!-- end #navigation -->
        </div> <!-- end container -->
    </div> <!-- end navbar-custom -->
</header>
<!-- End Navigation Bar-->