api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

# Views
from api.views import *

urlpatterns = [
    path('login/<slug:imei>/', Login.as_view()),
    path('sincronizacion/<int:ruta>/', Sincronizacion.as_view()),
    path('cierre/caja/<int:caja>/', CierreCaja.as_view()),
    path('transacciones/<slug:imei>/', Transacciones.as_view()),
    path('inversiones/<slug:imei>/', Inversiones.as_view()),
    path('rutas/', Rutas.as_view()),

    path('sincronizacion/movimientos/', SincronizacionMovimientos.as_view()),
    path('sincronizacion/clientes/editados/', SincronizacionClientesEditados.as_view()),
    path('sincronizacion/pagos/', SincronizacionPagos.as_view()),
    path('sincronizacion/clientes/', SincronizacionClientes.as_view()),
    path('sincronizacion/ventas/', SincronizacionVentas.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import Login, logout, PolitivasPrivacidad

from rest_framework.documentation import include_docs_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('',Login.as_view(), name="login" ),
    path('logout/', logout, name="logout"),
    path('rutas/', include('rutas.urls')),
    path('clientes/',include('clientes.urls')),
    path('ventas/',include('ventas.urls')),
    path('pagos/',include('pagos.urls')),
    path('caja/', include('caja.urls')),
    path('movimientos/', include('movimientos.urls')),
    path('retiros/', include('retiros.urls')),
    path('politicas_de_privacidad/',PolitivasPrivacidad.as_view() ,name="politivas_de_privacidad"),

    #URLS API
    path('docs/', include_docs_urls(title='Django API')),
    path('api/', include('api.urls')),


]

usuarios/urls.py
from usuarios.views import *
from django.urls import path
from usuarios.views import ComuinidadCrear, ComuinidadListar, UsuariosListar, \
								UsuarioCrear, UsuarioCrearAdmin, PermisosUsuario, UsuarioRutaActualizar
from usuarios.ajax import cambiar_estado_comunidad, cambiar_estado_usuario, \
							cambiar_permisos_secretaria
app_name = "usuarios"

urlpatterns = [
	#URLS de app Usuarios
	path('crear-comunidad/',ComuinidadCrear.as_view(), name="crear_comunidad"),
	path('listar-comunidad/',ComuinidadListar.as_view(), name="listar_comunidad"),
	path('listar-usuarios/',UsuariosListar.as_view(), name = "listar_usuarios" ),
	path('crear-usuarios/', UsuarioCrear.as_view(), name = "crear_usuarios"),
	path('crear-usuarios/admin', UsuarioCrearAdmin.as_view(), name = "crear_usuarios_admin"),
	path('editar-usuarios/<int:pk>/', UsuarioEditar.as_view(), name = "editar_usuario"),
	path('gestionar/<int:user>/', PermisosUsuario.as_view(), name="gestionar_usuario" ),
	path('agregar/rutas/secretaria/<int:pk>', UsuarioRutaActualizar.as_view(), name="rutas_secretaria"),

	#URLS de ajax Usuarios cambiar_estado_usuario UsuarioEditar
	path('estado/comunidad/',cambiar_estado_comunidad, name="cambiar_estado_comunidad" ),
	path('estado/usuario/',cambiar_estado_usuario, name="cambiar_estado_usuario" ),
	path('permisos/usuario/', cambiar_permisos_secretaria, name="cambiar_permisos_secretaria")
]

templates/bt_usuarios/crear_comunidad.html
{%extends "base/base.html"%}
{%block content%}
	<div class="wrapper b-wrapper">
        <div class="container-fluid">
        	<form action="{%url 'usuarios:crear_comunidad'%}" method="POST">{%csrf_token%}
	        	{{form.as_p}}
	        	<input type="submit" class="btn btn-primary" name="Guardar">
        	</form>
        </div>
    </div>
{%endblock%}

templates/bt_usuarios/crear_usuarios.html
{%extends "base/base.html"%}
{%block content%}
	<div class="wrapper b-wrapper">
        <div class="container-fluid">
        	<form action="{%url 'usuarios:crear_usuarios'%}" method="POST">{%csrf_token%}
	        	{{form.as_p}}
	        	<input type="submit" class="btn btn-primary" name="Guardar">
        	</form>
        </div>
    </div>
{%endblock%}

templates/bt_usuarios/editar_usuario.html
{%extends "base/base.html"%}
{%block content%}
<div class="row">
    <div class="col-12 col-md-8 col-lg-6 mx-auto">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">
                	EDITAR USUARIO	
                </h4>
            </div>

            <form class="px-4" action="{%url 'usuarios:editar_usuario' object.pk%}" method="POST">{%csrf_token%}
	        	{{form.as_p}}
	        	<a class="btn btn-success" href="{% url 'usuarios:listar_usuarios' %}">Cancelar</a>
	        	<input type="submit" class="btn btn-primary" name="Guardar">
        	</form>
        </div>
    </div>
</div>

{%endblock%}

templates/bt_usuarios/gestionar_permisios_rutas.html
{%extends 'base/base.html'%}
{%block content%}
<div class="row">  
    <div class="col-12"> 
    	{% if messages %}
          	<ul class="messages">
	            {% for message in messages %}
	              <li class="{{ message.tags }}">{{ message }}</li>
	            {% endfor %}
          	</ul>
        {% endif %}
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
            	<h4 class="header-title pt-2 bs-text-primary">GESTION DE PERMISOS Y RUTAS PARA LA SECRETARIA : {{perfil.first_name}}</h4>
            </div>
        </div>
    </div>
    <div class="col-16 col-md-6">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">PERMISOS</h4>
            </div>
            <div class="card-body pt-2 pb-0 bs-bg-grey-">
                <div class="row">
                	{%for contenido in permisos_secre%}
                    <div class="col-10 bs-border-bottom-grey pt-1"> 
                	   <h6 class="bs-text-black">{{contenido.name}}</h6>
                    </div>
                    <div class="col-2 bs-border-bottom-grey text-right py-1">
                    	{% if contenido.codename in perfil.permisos %}
                        <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}}, {{perfil.pk}})" type="checkbox" data-plugin="switchery" data-color="#88F674" data-secondary-color="#ED5565" data-size="small" checked />
                        {% else %}
                        	<input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}}, {{perfil.pk}})" type="checkbox" data-plugin="switchery" data-color="#88F674" data-secondary-color="#ED5565" data-size="small"/>
                        {%endif%}
                    </div>
                    {%endfor%}
                </div>
            </div>
        </div>
    </div>
    <div class="col-6 col-md-6">
    	<div class="card-box px-0 bs-border-primary">
	        <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
	            <h4 class="header-title pt-2 bs-text-primary">RUTAS</h4>
	        </div>
	        <div class="card-body pt-2 pb-0 bs-bg-grey-">
	            <div class="row">
	            	<form class="col-12 col-md-6" method="POST" action="{%url 'usuarios:rutas_secretaria' perfil.pk %}"> {%csrf_token%}
	                   {{form.as_p}}
	            		<input class="btn btn-primary" type="submit" name="Enviar" value="Guardar">
	            	</form>
                    <ul class="col-12 col-md-6">
                        {% for contenido in perfil.rutas.all %}
                            <li>{{contenido}}</li>
                        {% endfor %}
                    </ul>
	            </div>
	        </div>
	    </div>
	</div>
</div>

{%include "base/footer.html"%}
<script>
    function cambiarestado(permiso, usuario){
        $.ajax({
            type: "GET",
            url: "/usuarios/permisos/usuario/",
            data: {
                "id_permiso": permiso,
                "id_usuario": usuario, 
            },
        }).done(function(){
            // Agregamos los resultados al select
        });
    }
</script>
{%endblock%}

templates/bt_usuarios/listar_comunidad.html
{%extends 'base/base.html'%}
{%block content%}
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <div class="d-flex justify-content-between mb-3">
                <h4 class="m-t-0 header-title">Listado de Comunidades</h4>
                <a href="#custom-modal" class="btn btn-sm btn-primary waves-effect waves-light" data-animation="blur" data-plugin="custommodal" data-overlaySpeed="200" data-overlayColor="#36404a"><i class="ti-user"></i> Crear Comunidad</a>
            </div>

            <table id="datatable" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Creada</th>
                        <th>Nombre de Comunidad</th>
                        <th>Numero de Rutas</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                    {%if object_list%}
                        {%for contenido in object_list%}
                        <tr class="b-tr-td">
                            <td>
                                <div class="">
                                    <h5 class="m-0 p-0"><small class="b-font-weight-500">{{contenido.created}}</small></h5>
                                </div>
                            </td>
                            <td>
                                <div class="">
                                    <h5 class="m-0 p-0"><small class="b-font-weight-500">{{contenido.nombre}}</small></h5>
                                </div>
                            </td>
                            <td>
                                <div class="">
                                    <h5 class="m-0 p-0"><small class="b-font-weight-500">{{contenido.rutasPorComunidad}}</small></h5>
                                </div>
                            </td>
                            {%if not contenido.estado%}
                                <td class="b-td-acciones">  
                                    <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#88F674" data-secondary-color="#ED5565" data-size="small"/>
                                </td>
                            {%else%}
                                <td class="b-td-acciones">  
                                    <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#ED5565" data-secondary-color="#88F674" data-size="small"/>
                            {%endif%}
                        </tr>
                        {%endfor%}
                    {%endif%}
                </tbody>
            </table>
        </div>
    </div>
</div> <!-- end row -->
<div id="custom-modal" class="modal-demo">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">CREAR COMUNIDAD</h4>
    <form action="{%url 'usuarios:crear_comunidad'%}" method="POST">{%csrf_token%}
        <div class="custom-modal-text">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="nombre" for="field-1" class="control-label">Nombre</label>
                            {{form.nombre}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <a class="btn btn-secondary" href="">Cancelar</a>
                            <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{%include "base/footer.html"%}
<script>
    function cambiarestado(key){
        $.ajax({
            type: "GET",
            url: "/usuarios/estado/comunidad/",
            data: {
                "id_comunidad": key,
            },
        }).done(function(){
            // Agregamos los resultados al select
        });
    }
</script>
{%endblock%}

templates/bt_usuarios/listar_usuarios.html
{%extends 'base/base.html'%}
{%block content%}

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">Listado de Usuarios</h4>
                <a href="#custom-modal" class="btn btn-sm btn-primary waves-effect waves-light" data-animation="blur" data-plugin="custommodal" data-overlaySpeed="200" data-overlayColor="#36404a"><i class="ti-user"></i> Crear Usuario</a>
                <!--<button type="button" class="btn btn-sm btn-primary waves-effect waves-light" data-toggle="modal" data-target="#con-close-modal">Crear Ruta</button>-->
            </div>

            <div class="table-responsive-md">
                <table id="datatable" class="table table-bordered table-sm dataTable">
                    <thead class="bs-bg-light bs-text-primary text-center">
                        <tr> 
                            <th>NickName</th>
                            <th>PrimerNombre</th>
                            <th>Comunidad</th>
                            <th>Roll</th>
                            <th>Logueo</th>
                            <th>Cambiar Contraseña</th>
                            <th>Gestion Permisos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%if object_list%}
                            {%for contenido in object_list%}
                            <tr class="bs-table-sm">
                                <td align="center">{{contenido.username}}</td>
                                <td align="center">{{contenido.first_name}}</td>
                                <td align="center">{{contenido.comunidad}}</td>
                                <td align="center">
                                    {%if not contenido.is_staff%}
                                        {%if contenido.admin_comunidad%}
                                            Administrador Comunidad
                                        {%else%}
                                            {%if contenido.admin_secretaria%}
                                                Administrador Secretarias
                                            {%else%}
                                                Secretarias
                                            {%endif%}
                                        {%endif%}
                                    {%else%}
                                        Super Administrador
                                    {%endif%}
                                </td>
                                <td align="center">
                                    {%if request.user.pk != contenido.pk%}
                                        {%if not contenido.is_active%}
                                            <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#88F674" data-secondary-color="#ED5565" data-size="small"/>
                                        {%else%}
                                            <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#ED5565" data-secondary-color="#88F674" data-size="small"/>
                                        {%endif%}
                                    {%else%}
                                    {%endif%}
                                </td>
                                <td align="center" width="50px">
                                    <a title="Editar" href="{%url 'usuarios:editar_usuario' contenido.pk%}"> <i class="ti ti-pencil-alt bs-font-20 bs-text-primary px-2"></i></a>
                                </td>    
                                <td align="center" width="50px">
                                    {% if request.user.pk != contenido.pk and contenido.secretaria%}
                                    <a title="Gestionar Permisos" href="{% url 'usuarios:gestionar_usuario' contenido.pk %}"> <i class="ti ti-settings"></i> </a>
                                    {%endif%}
                                </td>
                            </tr>
                            {%endfor%}
                        {%endif%}
                    </tbody>
                </table>
            </div
        </div>
    </div>
</div> <!-- end row -->
<div id="custom-modal-editar" class="modal-demo">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">CREAR USUARIO ADMIN</h4>
    <form action="{%url 'usuarios:crear_usuarios_admin'%}" method="POST">{%csrf_token%}
        <div class="custom-modal-text">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="id_first_name1" for="field-12" class="control-label">Nombre</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_password11" for="field-12" class="control-label">Contraseña</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_password21" for="field-12" class="control-label">Confirmar Contraseña</label>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <a class="btn btn-secondary" href="">Cancelar</a>
                            <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{%if perms.usuarios.is_admincomunidad and not user.is_superuser%}
    <div id="custom-modal" class="modal-demo">
        <button type="button" class="close" onclick="Custombox.close();">
            <span>&times;</span><span class="sr-only">Close</span>
        </button>
        <h4 class="custom-modal-title">CREAR USUARIO ADMIN</h4>
        <form action="{%url 'usuarios:crear_usuarios_admin'%}" method="POST">{%csrf_token%}
            <div class="custom-modal-text">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label name="id_first_name" for="field-1" class="control-label">Nombre</label>
                                {{form.first_name}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label name="id_username" for="field-1" class="control-label">Nick Name</label>
                                {{form.username}}
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label name="id_username" for="field-1" class="control-label">Roll De Usuario</label>
                                {{form.status}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label name="id_password1" for="field-1" class="control-label">Contraseña</label>
                                {{form.password1}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label name="id_password2" for="field-1" class="control-label">Confirmar Contraseña</label>
                                {{form.password2}}
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group no-margin">
                                <a class="btn btn-secondary" href="">Cancelar</a>
                                <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{%else%}
<div id="custom-modal" class="modal-demo">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">CREAR USUARIO</h4>
    <form action="{%url 'usuarios:crear_usuarios'%}" method="POST">{%csrf_token%}
        <div class="custom-modal-text">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_first_name" for="field-1" class="control-label">Nombre</label>
                            {{form.first_name}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_username" for="field-1" class="control-label">Nick Name</label>
                            {{form.username}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="id_comunidad" for="field-1" class="control-label">Comunidad</label>
                            {{form.comunidad}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="id_username" for="field-1" class="control-label">Roll De Usuario</label>
                            {{form.status}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_password1" for="field-1" class="control-label">Contraseña</label>
                            {{form.password1}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label name="id_password2" for="field-1" class="control-label">Confirmar Contraseña</label>
                            {{form.password2}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <a class="btn btn-secondary" href="">Cancelar</a>
                            <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{%endif%}
{%include "base/footer.html"%}
<script>
    function cambiarestado(key){
        $.ajax({
            type: "GET",
            url: "/usuarios/estado/usuario/",
            data: {
                "id_usuario": key,
            },
        }).done(function(){
            // Agregamos los resultados al select
        });
    }
</script>

{%endblock%}