api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

# Views
from api.views import *

urlpatterns = [
    path('login/<slug:imei>/', Login.as_view()),
    path('sincronizacion/<int:ruta>/', Sincronizacion.as_view()),
    path('cierre/caja/<int:caja>/', CierreCaja.as_view()),
    path('transacciones/<slug:imei>/', Transacciones.as_view()),
    path('inversiones/<slug:imei>/', Inversiones.as_view()),
    path('rutas/', Rutas.as_view()),

    path('sincronizacion/movimientos/', SincronizacionMovimientos.as_view()),
    path('sincronizacion/clientes/editados/', SincronizacionClientesEditados.as_view()),
    path('sincronizacion/pagos/', SincronizacionPagos.as_view()),
    path('sincronizacion/clientes/', SincronizacionClientes.as_view()),
    path('sincronizacion/ventas/', SincronizacionVentas.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import Login, logout, PolitivasPrivacidad

from rest_framework.documentation import include_docs_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('',Login.as_view(), name="login" ),
    path('logout/', logout, name="logout"),
    path('rutas/', include('rutas.urls')),
    path('clientes/',include('clientes.urls')),
    path('ventas/',include('ventas.urls')),
    path('pagos/',include('pagos.urls')),
    path('caja/', include('caja.urls')),
    path('movimientos/', include('movimientos.urls')),
    path('retiros/', include('retiros.urls')),
    path('politicas_de_privacidad/',PolitivasPrivacidad.as_view() ,name="politivas_de_privacidad"),

    #URLS API
    path('docs/', include_docs_urls(title='Django API')),
    path('api/', include('api.urls')),


]

retiros/urls.py
from django.urls import path
from retiros.views import TransaccionCrear, TransaccionListar, TransaccionEditar, TransaccionEliminar, \
							InversionListar, InversionCrear, InversionEditar, Buscar

app_name = "retiros"

urlpatterns = [
	path('listar/', TransaccionListar.as_view(), name = "listar_retiros"),
	path('crear/', TransaccionCrear.as_view(), name = "crear_retiro"),
	path('editar/<int:pk>/', TransaccionEditar.as_view(), name = "editar_retiro"),
	path('eliminar/<int:pk>', TransaccionEliminar.as_view(), name = "eliminar_retiro"),

	path('inversiones/listar', InversionListar.as_view(), name = "listar_inversiones"),
	path('inversiones/crear/', InversionCrear.as_view(), name = "crear_inversion"),
	path('inversiones/editar/<int:pk>/', InversionEditar.as_view(), name = "editar_inversion"),

	path('busqueda/<slug:busqueda>/', Buscar.as_view(), name="busqueda"),
]

templates/bt_retiros/editar_inversiones.html
{%extends "base/base.html"%}
{%block content%}
<div class="row">
    <div class="col-12 col-md-8 col-lg-6 mx-auto">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">
                	EDITAR INVERSION
                </h4>
            </div>

            <form class="px-4" action="{%url 'retiros:editar_inversion' object.pk%}" method="POST">{%csrf_token%}
	        	{{form.as_p}}
	        	<a class="btn btn-success" href="{% url 'retiros:listar_inversiones' %}">Cancelar</a>
	        	<input type="submit" class="btn btn-primary" name="Guardar">
        	</form>
        </div>
    </div>
</div>
{%include "base/footer.html"%}
{%endblock%}

templates/bt_retiros/editar_retiros.html
{%extends "base/base.html"%}
{%block content%}
<div class="row">
    <div class="col-12 col-md-8 col-lg-6 mx-auto">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">
                	EDITAR RETIRO
                </h4>
            </div>

            <form class="px-4" action="{%url 'retiros:editar_retiro' object.pk%}" method="POST">{%csrf_token%}
	        	{{form.as_p}}
	        	<a class="btn btn-success" href="{% url 'retiros:listar_retiros' %}">Cancelar</a>
	        	<input type="submit" class="btn btn-primary" name="Guardar">
        	</form>
        </div>
    </div>
</div>
{%include "base/footer.html"%}
{%endblock%}

templates/bt_retiros/listar_inversiones.html
{%extends 'base/base.html'%}
{%block content%}
<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">FILTRAR POR FECHAS</h4>
            </div>

            <form class="px-3" action="{%url 'retiros:busqueda' 'transaccion'%}" name="periodo-form" method="GET">
                <div class="form-row">
                    <div class="col-12 col-md-4 col-lg-3">
                        <input type="date" class="form-control" name="inicio" placeholder="Fecha Inicio" />
                    </div>
                    <div class="col-12 col-md-4 col-lg-3 py-3 py-md-0">
                        <input type="date" class="form-control" name="fin" placeholder="Fecha Fin" />
                    </div>
                    <div class="col-12 col-md-4">
                        <input type="submit" value="Resumen" class="btn btn-primary waves-effect waves-light">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div> <!-- end row -->

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">Listado de Inversiones</h4>
                <a href="#custom-modal" class="btn btn-sm btn-primary waves-effect waves-light" data-animation="blur" data-plugin="custommodal" data-overlaySpeed="200" data-overlayColor="#36404a"><i class=""></i>Crear Inversion</a>
            </div>  
            
            <!-- Inicio table responsive -->
            <div class="table-responsive-md">
                <table id="datatable" class="table table-bordered table-sm dataTable table-hover">
                    <thead class="bs-bg-light bs-text-primary text-center">
                        <tr> 
                            <th>Ruta Destino</th>
                            <th>Valor</th>  
                            <th>Origen</th>
                            <th>Fecha</th>
                            <th>Usuario</th>
                            <th width="60px"></th>
                            <th width="60px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {%if object_list%}
                        {%for contenido in object_list%}
                        <tr class="b-tr-td">
                            <td align="center">{{contenido.ruta_destino}}</td>
                            <td align="center">{{contenido.valor}}</td>
                            {% if contenido.ruta_origen %}
                                <td align="center">{{contenido.ruta_origen}}</td>
                            {% else %} 
                                <td align="center">{{contenido.origen}}</td>   
                            {% endif %}    
                            <td align="center">{{contenido.created.date}}</td>
                            <td align="center">{{contenido.usuario.get_full_name}}</td>
                            <td width="50px" align="center">
                                <a title="Editar" href="{%url 'retiros:editar_inversion' contenido.pk %}"> <i class="ti ti-pencil-alt bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                            <td width="50px" align="center">
                                <a title="Eliminar" href="#" onclick="eliminar({{contenido.pk}})"> <i class="ti ti-trash bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                        </tr>
                        {%endfor%}
                    {%endif%}
                    </tbody>
                </table>
            </div>
            <!-- End table responsive -->    
        </div>
    </div>
</div> <!-- end row -->

{%include "base/footer.html"%}
<script type="text/javascript">
    function eliminar(pk){
    swal({
          title: "Estas seguro que quieres eliminar??",
          text: "Si eliminas este registro se eliminara todo en cadena, relaciones que esten asociadas a este retiro!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Su objeto ha sido eliminado!", {
            icon: "success",
            });
            window.location.replace("/retiros/eliminar/"+pk);
          } else {
            swal("Ok!");
          }
        });
    };
</script>
<div id="custom-modal" class="modal-demo">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">Crear Inversion</h4>
    <form action="{%url 'retiros:crear_inversion'%}" method="POST">{%csrf_token%}
        <div class="custom-modal-text">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="1_ruta" for="field-1" class="control-label">Rutas Destino</label>
                            {{form.ruta_destino}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="l_valor" for="field-1" class="control-label">Cantidad a depositar</label>
                            {{form.valor}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="l_cuenta_bancaria" for="field-1" class="control-label">De que ruta viene?</label>
                            {{form.ruta_origen}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="l_cuenta_bancaria" for="field-1" class="control-label">O de que origen?</label>
                            {{form.origen}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group" style="display:none;">
                            <label name="l_password" for="field-1" class="control-label">Usuario</label>                           
                            <select name="usuario" id="id_usuario">
                              <option value="{{request.user.pk}}" selected="">{{request.user}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <a class="btn btn-secondary" href="">Cancelar</a>
                            <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!--
<script>
    function cambiarestado(key){
        $.ajax({
            type: "GET",
            url: "/usuarios/estado/comunidad/",
            data: {
                "id_comunidad": key,
            },
        }).done(function(){
            // Agregamos los resultados al select
        });
    }
</script>-->
{%endblock%}
a

templates/bt_retiros/listar_retiros.html
{%extends 'base/base.html'%}
{%block content%}

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">FILTRAR POR FECHAS</h4>
            </div>

            <form class="px-3" action="{%url 'retiros:busqueda' 'transaccion'%}" name="periodo-form" method="GET">
                <div class="form-row">
                    <div class="col-12 col-md-4 col-lg-3">
                        <input type="date" class="form-control" name="inicio" placeholder="Fecha Inicio" />
                    </div>
                    <div class="col-12 col-md-4 col-lg-3 py-3 py-md-0">
                        <input type="date" class="form-control" name="fin" placeholder="Fecha Fin" />
                    </div>
                    <div class="col-12 col-md-4">
                        <input type="submit" value="Resumen" class="btn btn-primary waves-effect waves-light">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div> <!-- end row -->

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">Listado de Retiros</h4>
                <a href="#custom-modal" class="btn btn-sm btn-primary waves-effect waves-light" data-animation="blur" data-plugin="custommodal" data-overlaySpeed="200" data-overlayColor="#36404a"><i class=""></i>Crear Retiro</a>
            </div>
            
            <!-- Inicio table responsive -->
            <div class="table-responsive-md">
                <table id="datatable" class="table table-bordered table-sm dataTable table-hover">
                    <thead class="bs-bg-light bs-text-primary text-center">
                        <tr> 
                            <th>Ruta</th>
                            <th>Valor</th>
                            <th>Cuenta</th>
                            <th>Fecha</th>
                            <th>Usuario</th>
                            <th width="60px"></th>
                            <th width="60px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {%if object_list%}
                        {%for contenido in object_list%}
                        <tr class="b-tr-td">
                            <td align="center">{{contenido.rutas}}</td>
                            <td align="center">{{contenido.valor}}</td>
                            <td align="center">{{contenido.cuenta_bancaria}}</td>
                            <td align="center">{{contenido.created.date}}</td>
                            <td align="center">{{contenido.usuario.get_full_name}}</td>
                            <td width="50px" align="center">
                                <a title="Editar" href="{%url 'retiros:editar_retiro' contenido.pk %}"> <i class="ti ti-pencil-alt bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                            <td width="50px" align="center">
                                <a title="Eliminar" href="#" onclick="eliminar({{contenido.pk}})"> <i class="ti ti-trash bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                        </tr>
                        {%endfor%}
                    {%endif%}
                    </tbody>
                </table>
            </div>
            <!-- End table responsive -->    
        </div>
    </div>
</div> <!-- end row -->

{%include "base/footer.html"%}
<script type="text/javascript">
    function eliminar(pk){
    swal({
          title: "Estas seguro que quieres eliminar??",
          text: "Si eliminas este registro se eliminara todo en cadena, relaciones que esten asociadas a este retiro!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Su objeto ha sido eliminado!", {
            icon: "success",
            });
            window.location.replace("/retiros/eliminar/"+pk);
          } else {
            swal("Ok!");
          }
        });
    };
</script>
<div id="custom-modal" class="modal-demo">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">Crear Retiro</h4>
    <form action="{%url 'retiros:crear_retiro'%}" method="POST">{%csrf_token%}
        <div class="custom-modal-text">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="1_ruta" for="field-1" class="control-label">Rutas</label>
                            {{form.rutas}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="l_valor" for="field-1" class="control-label">Cantidad a retirar</label>
                            {{form.valor}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label name="l_cuenta_bancaria" for="field-1" class="control-label">Numero de cuenta</label>
                            {{form.cuenta_bancaria}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group" style="display:none;">
                            <label name="l_password" for="field-1" class="control-label">Usuario</label>                           
                            <select name="usuario" id="id_usuario">
                              <option value="{{request.user.pk}}" selected="">{{request.user}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <a class="btn btn-secondary" href="">Cancelar</a>
                            <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!--
<script>
    function cambiarestado(key){
        $.ajax({
            type: "GET",
            url: "/usuarios/estado/comunidad/",
            data: {
                "id_comunidad": key,
            },
        }).done(function(){
            // Agregamos los resultados al select
        });
    }
</script>-->
{%endblock%}
a