api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

# Views
from api.views import *

urlpatterns = [
    path('login/<slug:imei>/', Login.as_view()),
    path('sincronizacion/<int:ruta>/', Sincronizacion.as_view()),
    path('cierre/caja/<int:caja>/', CierreCaja.as_view()),
    path('transacciones/<slug:imei>/', Transacciones.as_view()),
    path('inversiones/<slug:imei>/', Inversiones.as_view()),
    path('rutas/', Rutas.as_view()),

    path('sincronizacion/movimientos/', SincronizacionMovimientos.as_view()),
    path('sincronizacion/clientes/editados/', SincronizacionClientesEditados.as_view()),
    path('sincronizacion/pagos/', SincronizacionPagos.as_view()),
    path('sincronizacion/clientes/', SincronizacionClientes.as_view()),
    path('sincronizacion/ventas/', SincronizacionVentas.as_view()),
]

clientes/urls.py
from django.urls import path

from clientes.views import ClienteCrear, ClienteListar, ClienteActualizar, ClienteEliminar, ClienteSinVentaActiva
from clientes.ajax import editar_estado
app_name = "clientes"

urlpatterns = [
	path('listar/<int:id_ruta>/', ClienteListar.as_view(), name = "listar_clientes"),
	path('listar/<int:id_ruta>/sin-venta-activa/', ClienteSinVentaActiva.as_view(), name = "listar_clientes_sin_venta_activa"),
	path('crear/', ClienteCrear.as_view(), name = "crear_cliente"),
	path('editar/<int:pk>/<int:ruta>/',ClienteActualizar.as_view(), name = "editar_cliente"),
	path('eliminar/<int:pk>/', ClienteEliminar.as_view(), name = "eliminar_cliente"),

	#Ajax
	path('estado/', editar_estado, name="editar_estado")
]	

project/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import Login, logout, PolitivasPrivacidad

from rest_framework.documentation import include_docs_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('',Login.as_view(), name="login" ),
    path('logout/', logout, name="logout"),
    path('rutas/', include('rutas.urls')),
    path('clientes/',include('clientes.urls')),
    path('ventas/',include('ventas.urls')),
    path('pagos/',include('pagos.urls')),
    path('caja/', include('caja.urls')),
    path('movimientos/', include('movimientos.urls')),
    path('retiros/', include('retiros.urls')),
    path('politicas_de_privacidad/',PolitivasPrivacidad.as_view() ,name="politivas_de_privacidad"),

    #URLS API
    path('docs/', include_docs_urls(title='Django API')),
    path('api/', include('api.urls')),


]

rutas/urls.py
from rutas.views import Base, RutaListar, RutaCrear, RutaEditar, ImeiListar, ImeiCrear, ImeiEditar, RutaEliminar, ImeiEliminar
from django.urls import path
from rutas.ajax import cambiar_estado, cierre_ruta

app_name = "rutas"

urlpatterns = [
    path('base/', Base.as_view(), name="base"),
    path('listar/', RutaListar.as_view(), name = "listar_rutas"),
    path('crear/', RutaCrear.as_view(), name = "crear_ruta"),
    path('editar/<int:pk>/', RutaEditar.as_view(), name = "editar_ruta"),
    path('listar/imei/', ImeiListar.as_view(), name = "listar_imei"),
    path('crear/imei/', ImeiCrear.as_view(), name = "crear_imei"),
    path('editar/imei/<int:pk>/', ImeiEditar.as_view(), name = "editar_imei"),
    path('eliminar/<int:pk>/',RutaEliminar.as_view(), name='eliminar'),
    path('imei/eliminar/<int:pk>/',ImeiEliminar.as_view(), name='eliminar_imei'),

    #AJAX
    path('estado/', cambiar_estado, name = "cambiar_estado_ruta"),
    path('cierre/ruta/', cierre_ruta, name = "pagos_cierre_ruta"),

]

ventas/urls.py
from django.urls import path
from ventas.views import VentaCrear, VentaLisar, VentaActualizar, VentaEliminar, VentasActivas

app_name="ventas"

urlpatterns = [
	path('listar/<int:cliente>/',VentaLisar.as_view(), name ="listar_ventas" ),
	path('crear/', VentaCrear.as_view(), name="crear_venta"),
	path('editar/<int:pk>/', VentaActualizar.as_view(), name="actualizar_venta"),
	path('editar/<int:pk>/<int:caja>', VentaActualizar.as_view(), name="actualizar_venta_caja"),
	path('eliminar/<int:pk>/', VentaEliminar.as_view(), name="eliminar_venta"),
	path('eliminar/<int:pk>/<int:caja>', VentaEliminar.as_view(), name="eliminar_venta_caja"),
	path('listar/ruta/<int:idruta>', VentaLisar.as_view(), name ="listar_ventas_ruta"),
	path('listar/activas/<int:idruta>', VentasActivas.as_view(), name = 'listar_ventas_activas'),
]

templates/bt_clientes/editar_cliente.html
{%extends "base/base.html"%}
{%block content%}
<div class="row">
    <div class="col-12 col-md-8 col-lg-6 mx-auto">
        <div class="card-box px-0 bs-border-primary">
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">
                    {% if object %}
                    Editar Cliente
                    {% else %}
                    Crear Cliente
                    {% endif %}
                </h4>
            </div>

            {%if object%}
            <form class="px-4" action="{%url 'clientes:editar_cliente' object.pk ruta%}" method="POST">{%csrf_token%}
            {%else%}
            <form class="px-4" action="{%url 'clientes:crear_cliente'%}" method="POST">{%csrf_token%}
            {%endif%}
                {{form.as_p}}
                <a class="btn btn-success" href="#">Cancelar</a>
                <input type="submit" class="btn btn-primary" value="Guardar">
            </form>
        </div>
    </div>
</div>
{%include "base/footer.html"%}
{%endblock%}

templates/bt_clientes/listar_clientes.html
{%extends 'base/base.html'%}
{%block content%}

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">Listado de Clientes - Ruta {{object_list.first.ruta}}</h4>
                {% if perms.usuarios.crear_clientes %}
                    <button type="button" class="btn btn-sm btn-primary waves-effect waves-light" data-toggle="modal" data-target="#con-close-modal">Crear Cliente</button>
                {% endif %}
            </div>

            <!--<div class="px-5">
                <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar por Codigo..." title="Type in a name">
            </div>-->
            
            <!-- Inicio table responsive -->
            <div class="table-responsive-md">
                <table id="datatable" class="table table-bordered table-sm dataTable table-hover">
                    <thead class="bs-bg-light bs-text-primary text-center">
                        <tr> 
                            <th>ID</th>
                            <th>Cliente</th>
                            <th>Alias</th>
                            {% if perms.usuarios.inactivar_clientes %}
                                <th>EST</th>
                            {% endif %}
                            <th>List</th>
                            {% if perms.usuarios.crear_ventas %}
                                <th>Crear</th>
                            {% endif %}
                            <th>EDV</th>
                            {% if perms.usuarios.eliminar_clientes %}
                                <th>ELV</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                    {%if object_list%}
                        {%for contenido in object_list %}
                        <!-- Error class bd-table-sm -->
                        <tr class="bs-table-s">
                            <td width="50" align="center">{{contenido.pk}} </td>
                            <td align="center">{{contenido.cliente}}</td>
                            <td align="center">{{contenido.cliente.alias}}</td>
                            {% if perms.usuarios.inactivar_clientes %}
                                <td align="center">
                                    {%if not contenido.activo%}
                                        <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#ED5565" data-secondary-color="#88F674" data-size="small" checked />
                                    {%else%}
                                        <input id="check" class="btn btn-primary" onchange="cambiarestado({{contenido.pk}})" type="checkbox" data-plugin="switchery" data-color="#ED5565" data-secondary-color="#88F674" data-size="small" />
                                    {%endif%}
                                </td>
                            {% endif %}
                            <td width="50px" align="center">
                                <a title="Listar Venta" href="{%url 'ventas:listar_ventas' contenido.pk %}"> <i class="ti ti-agenda bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                            {% if perms.usuarios.crear_ventas %}
                                <td width="50px" align="center">
                                    {%if not contenido.ventas_activas %}
                                        <button onclick="pk_modelo({{contenido.pk}})" type="button" class="btn btn-btn" data-toggle="modal" data-target="#con-close-modal-venta" title="Crear Venta"> <i class="ti ti-save bs-font-20 bs-text-primary px-2"></i></button>
                                    {%endif%}
                                </td>
                            {% endif %}
                            <td width="50px" align="center">
                                <a title="Editar" href="{%url 'clientes:editar_cliente' contenido.cliente.pk contenido.ruta.pk%}"> <i class="ti ti-pencil-alt bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                            {% if perms.usuarios.eliminar_clientes %}
                            <td width="50px" align="center">
                                <a title="Eliminar" href="#" onclick="eliminar({{contenido.pk}})"> <i class="ti ti-trash bs-font-20 bs-text-primary px-2"></i></a>
                            </td>
                            {% endif %}
                        </tr>
                        {%endfor%}
                    {%endif%}
                    </tbody>
                </table>
            </div>
            <!-- End table responsive -->    
        </div>
    </div>
</div> <!-- end row -->

<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Crear Cliente</h4>
                <!-- <a class="btn btn-rounded btn-outline-primary" href="{% url 'rutas:crear_imei' %}" target="_self">Crear Imei</a> -->
            </div>
            <form action="{%url 'clientes:crear_cliente'%}" method="POST">{%csrf_token%}
                <div class="custom-modal-text">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">Nombre</label>
                                    {{form.nombre}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">Apellido</label>
                                    {{form.apellido}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">CPF</label>
                                    {{form.cpf}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">Alias</label>
                                    {{form.alias}}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">Direccion</label>
                                    {{form.direccion}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label name="nombre" for="field-1" class="control-label">Celular</label>
                                    {{form.celular}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="hidden" name="ruta" value="{{id_ruta}}">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group no-margin">
                                    <a class="btn btn-secondary" href="">Cancelar</a>
                                    <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div><!-- /.modal -->

<div id="con-close-modal-venta" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Crear Venta</h4>
                <!-- <a class="btn btn-rounded btn-outline-primary" href="{% url 'rutas:crear_imei' %}" target="_self">Crear Imei</a> -->
            </div>
            <form action="{%url 'ventas:crear_venta'%}" method="POST">{%csrf_token%}
                <div class="custom-modal-text">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{form2}}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group no-margin">
                                    <a class="btn btn-secondary" href="">Cancelar</a>
                                    <input type="submit" name="Guardar" value="Guardar" class="btn btn-primary" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div><!-- /.modal -->
{%include "base/footer.html"%}

<script>
function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("datatable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

<script>
    function cambiarestado(key){
        $.ajax({
            type: "GET",
            url: "/clientes/estado/",
            data: {
                "id_cliente": key,
            },
        }).done(function(){
            // Agregamos los resultados al select
            console.log("True");
        });
    }
</script>
<script type="text/javascript">
    function pk_modelo(pk){
        document.getElementById("id_id_cliente_ruta").value = pk;
        console.log(pk);

    }
</script>
<script type="text/javascript">
    function eliminar(pk){
    swal({
          title: "Estas seguro que quieres eliminar??",
          text: "Si eliminas este registro se eliminara todo en cadena, relaciones que esten asociadas a este cliente!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Su objeto ha sido eliminado!", {
            icon: "success",
            });
            window.location.replace("/clientes/eliminar/"+pk);
          } else {
            swal("Ok!");
          }
        });
    };
</script>
{%endblock%}

templates/bt_clientes/listar_clientes_sin_venta_activa.html
{%extends 'base/base.html'%}
{%block content%}

<div class="row">
    <div class="col-12">
        <div class="card-box px-0 bs-border-primary">
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            <div class="d-flex justify-content-between mb-3 bs-bg-grey-light card-header rounded-0 bs-border-y-primary">
                <h4 class="header-title pt-2 bs-text-primary">Listado de Clientes - Ruta {{object_list.first.ruta}}</h4>
                <button type="button" class="btn btn-sm btn-primary waves-effect waves-light" data-toggle="modal" data-target="#con-close-modal">Crear Cliente</button>
            </div>
            
            <!-- Inicio table responsive -->
            <div class="table-responsive-md">
                <table id="datatable" class="table table-bordered table-sm dataTable table-hover">
                    <thead class="bs-bg-light bs-text-primary text-center">
                        <tr> 
                            <th>ID</th>
                            <th>Cliente</th>
                            <th>Alias</th>
                            <th>Fecha Ult. Venta</th>
                            <th>Valor Ult. Venta</th>
                            <th>Info</th>
                            <th>Valor Neto</th>
                            <th>Dias Demorados</th>
                        </tr>
                    </thead>
                    <tbody>
                    {%if object_list%}
                        {%for contenido in object_list %}
                        {%if contenido.sin_venta_activa%}
                        <!-- Error class bd-table-sm -->
                            <tr class="bs-table-s">
                                <td width="50" align="center">{{contenido.pk}} </td>
                                <td align="center"><a href="{%url 'ventas:listar_ventas' contenido.pk %}">{{contenido.cliente}}</a></td>
                                <td align="center">{{contenido.cliente.alias}}</td>
                                <td align="center">{{contenido.ultima_venta.created}}</td>
                                <td align="center">{{contenido.ultima_venta.valor}}</td>
                                <td align="center">{{contenido.ultima_venta.interes}}% a {{contenido.ultima_venta.cuotas}} dias</td>
                                <td align="center">{{contenido.ultima_venta.valor_venta_interes|floatformat:2}}</td>
                                <td align="center">{{contenido.ultima_venta.dias}}</td>
                            </tr>
                        {%endif%}
                        {%endfor%}
                    {%endif%}
                    </tbody>
                </table>
            </div>
            <!-- End table responsive -->    
        </div>
    </div>
</div> <!-- end row -->

{%include "base/footer.html"%}
{%endblock%}